In [1]:
import pandas as pd

def load_data():
    url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
    html = pd.read_html(url, header = 0)
    df = html[0]
    return df

In [2]:
df = load_data()
df

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,AOS,A. O. Smith,reports,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
3,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [8]:
#  Setores de empresas
setor_unico = df['GICS Sector'].unique()
setor_unico

array(['Industrials', 'Health Care', 'Information Technology',
       'Communication Services', 'Consumer Staples',
       'Consumer Discretionary', 'Utilities', 'Financials', 'Materials',
       'Real Estate', 'Energy'], dtype=object)

In [7]:
#  Quantidade de setores de empresas
len(setor_unico)

11

In [9]:
#  Empresas por setor
setor = df.groupby('GICS Sector')
setor.describe()

                         CIK                                                   \
                       count          mean            std      min        25%
GICS Sector
Communication Services  26.0  1.094660e+06  521922.541174  18926.0  752994.75
Consumer Discretionary  56.0  8.620841e+05  454741.225170  27419.0  759791.50
Consumer Staples        33.0  4.185174e+05  583783.310585   7084.0   24545.00
Energy                  21.0  8.548145e+05  635563.925529   4447.0  101778.00
Financials              66.0  6.369112e+05  537329.687765   4962.0   71386.25
Health Care             64.0  8.222880e+05  531850.572835   1800.0  312903.00
Industrials             72.0  6.702700e+05  589191.365805   4281.0   77103.50
Information Technology  76.0  9.225350e+05  504187.670359   2488.0  764360.50
Materials               28.0  8.369064e+05  699182.236462   2969.0   67840.25
Real Estate             32.0  9.460987e+05  368574.969659  34903.0  855145.75
Utilities               29.0  8.402204e+05  467422.045064   4904.0  731802.00


                              50%         75%        max
GICS Sector
Communication Services  1129179.0  1532807.75  1754301.0
Consumer Discretionary   918562.5  1130953.25  1590895.0
Consumer Staples          77476.0   865752.00  1679273.0
Energy                  1035002.0  1506307.00  1841666.0
Financials               739974.5  1118437.00  1601712.0
Health Care              880632.0  1100020.50  1821825.0
Industrials              737525.0  1062218.50  1783180.0
Information Technology   949462.5  1344081.75  1730168.0
Materials                915994.5  1419355.00  1755672.0
Real Estate              970545.5  1065508.25  1705696.0
Utilities                874761.0  1047862.00  1868275.0

In [11]:
#  Empresas por setor
setor.get_group('Energy')

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
44,APA,APA Corporation,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",1997-07-28,1841666,1954
57,BKR,Baker Hughes,reports,Energy,Oil & Gas Equipment & Services,"Houston, Texas",2017-07-07,1701605,2017
104,CVX,Chevron Corporation,reports,Energy,Integrated Oil & Gas,"San Ramon, California",1957-03-04,93410,1879
124,COP,ConocoPhillips,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",1957-03-04,1163165,2002
134,CTRA,Coterra,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",2008-06-23,858470,2021 (1989)
146,DVN,Devon Energy,reports,Energy,Oil & Gas Exploration & Production,"Oklahoma City, Oklahoma",2000-08-30,1090012,1971
148,FANG,Diamondback Energy,reports,Energy,Oil & Gas Exploration & Production,"Midland, Texas",2018-12-03,1539838,2007
176,EOG,EOG Resources,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",2000-11-02,821189,1999
191,XOM,ExxonMobil,reports,Energy,Integrated Oil & Gas,"Irving, Texas",1957-03-04,34088,1999
224,HAL,Halliburton,reports,Energy,Oil & Gas Equipment & Services,"Houston, Texas",1957-03-04,45012,1919
231,HES,Hess Corporation,reports,Energy,Integrated Oil & Gas,"New York City, New York",1984-05-31,4447,1919
275,KMI,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307,1997
296,MRO,Marathon Oil,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",1991-05-01,101778,1887
297,MPC,Marathon Petroleum,reports,Energy,Oil & Gas Refining & Marketing,"Findlay, Ohio",2011-07-01,1510295,2009 (1887)
353,OXY,Occidental Petroleum,reports,Energy,Oil & Gas Exploration & Production,"Houston, Texas",1982-12-31,797468,1920
357,OKE,Oneok,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",2010-03-15,1039684,1906
373,PSX,Phillips 66,reports,Energy,Oil & Gas Refining & Marketing,"Houston, Texas",2012-05-01,1534701,2012 (1917)
375,PXD,Pioneer Natural Resources,reports,Energy,Oil & Gas Exploration & Production,"Irving, Texas",2008-09-24,1038357,1997
411,SLB,Schlumberger,reports,Energy,Oil & Gas Equipment & Services,"CuraÃ§ao, Kingdom of the Netherlands",1965-03-31,87347,1926
466,VLO,Valero Energy,reports,Energy,Oil & Gas Refining & Marketing,"San Antonio, Texas",NaN,1035002,1980
492,WMB,Williams Companies,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,1908